#!/usr/bin/env bash

# Start up Windows programs from WSL. YMMV

for i in "$@" ; do
  if [[ "$i" =~ .*/.* ]]  &&  wslpath -aw -- "$i" 2>&1 > /dev/null ; then
    ARGS[ $((x+= 1)) ]=$(wslpath -aw -- $"$i"|sed -Ee 's/^[[:space:]]*(.+)[[:space:]]*/\1/')
  else
    ARGS[ $((x+= 1)) ]="$i"
  fi
done

cmd.exe /c start ${ARGS[*]}